---

Write a Python program to compute the eigenvalues and right eigenvectors of a given square array

---

In [63]:
import numpy as np
from numpy.linalg import eig
from sympy import Symbol, solve
# define square array

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
# eigenvector equation: Av = λv
# A = square matrix
# v = eigenvector of the matrix
# λ = eigenvalue scalar

# factorize
values, vectors = eig(a)
print(values, vectors)

[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16] [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [69]:
# manually calculate eigenvalues and eigenvectors
# define 2x2 eigenvalue calculator
def eigen_2(matrix):
    A = matrix
    L = Symbol('lambda')
    a, b, c, d = A[0,0], A[0,1], A[1,0], A[1,1]
    det = (a-L)*(d-L) - (b*c)
    eigenvalues = solve(det)
    

twos = np.matrix("7 8; 6 5")
eigen_2(twos)

[-1, 13]

In [74]:
# check output against eig function
values, vectors = eig(twos)
print("Built-in return:", values)
print("Manual return:", eigen_2(twos))

Built-in return: [13. -1.]
Manual return: [-1, 13]


In [ ]:
# define 2x2 eigenvector calculator
# eigenvector equation: Av = λv
# v = eigenvector, λ  = eigenvalue

In [80]:
# define 3x3 eigenvalue calculator
def eigen_3(matrix):
    A = matrix
    L = Symbol('lambda')
    a, b, c = A[0,0], A[0,1], A[0,2]
    d, e, f = A[1,0], A[1,1], A[1,2]
    g, h, i = A[2,0], A[2,1], A[2,2]
    co1 = (a-L)*((e-L)*(i-L)-(f*h))
    co2 = b*(d*(i-L)-(f*g))
    co3 = c*((d*h)-((e-L)*g))
    det = co1 - co2 + co3
    return solve(det) # returns a list

threes = np.matrix("-2 -4 2; -2 1 2; 4 2 5")
eigen_3(threes)

[-5, 3, 6]

In [76]:
# check output against eig function
values, vectors = eig(threes)
print("Built-in return:", values)
print("Manual return:", eigen_3(threes))

Built-in return: [-5.  3.  6.]
Manual return: [-5, 3, 6]


The built-in function returns an array, while the manual functions returns a list. I tried to output an array but I wasn't able to approximate the built-in output. 

I tried to write add a loop inside the function that would iterate through the length of the output values, substituting the values for Lambda to get the eigenvectors, but I a) could get this loop to work outside, but not inside, the function, and it also didn't match the output from eig:

In [ ]:
for i in range(len(values)):
    vec = (a-values[i])*(d-values[i]) - (b*c)
    vectors.append(vec)
    
return values, vectors

I tried to create an identity matrix to multiply against the Matrix minus Lambda in order to solve for x in:
(A - lambda * I) * x = 0, but I could not solve this either.

In [144]:
# create an identity matrix
def identity_m(size):
    # create an identity matrix of desired size
    I = np.zeros((size, size))
    for i in range(size):
        I[i][i] = 1
        
    return I

Then I was able to get as far as the below loop but I wasn't able to figure out how to reduce the matrices:

```
vecs = []

for i in range(len(values)):
    vec = A - values[i]*I
    vecs.append(vec)
```

I could not return the eigenvectors

---
Write a Python program to compute the factor of a given array by Singular Value Decomposition

---

In [22]:
from scipy.linalg import svd

# factorize

U, s, V = svd(a)
print(U, s, V)

[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]] [1.68481034e+01 1.06836951e+00 3.33475287e-16] [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


---
Write a Python program to compute the determinant of an array

---

In [85]:
# determinant of the matrix
# product of all the eigenvalues of the matrix

from numpy.linalg import det

#initialize matrix
a = np.arange(1,10).reshape(3,3)

# calculate determinant
B = det(a)
print("Determinant:", B)

Determinant: -9.51619735392994e-16


In [23]:
det(a)

-9.51619735392994e-16

In [88]:
# examine the array
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
# try using np.matrix to see if the output is the same
a = np.matrix("1 2 3; 4 5 6; 7 8 9")
det(a)

-9.51619735392994e-16

In [90]:
# examine the matrix
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
# manually perform the caluclation:

# variable1 (v1) = a(ei - fh)
v1 = 1 * (5*9 - 6*8)
# variable2 (v2) = b(di - fg)
v2 = 2 * (4*9 - 6*7)
# variable3 (v3) = c(dh - eg) 
v3 = 3 * (4*8 - 5*7)

# a(ei - fh) - b(di - fg) + c(dh - eg)
v1 - v2 + v3

0

Despite substantial research, I can not resolve why there is this discrepency in the outputs. I tried building matrix calculators to handle a 2x2 matrix, a 3x3 matrix, and then to break down larger matrices into 3x3 matrices.

In [139]:
def det_2(matrix):
    # calculates determinant of a 2x2 matrix
    if matrix.shape[1] == 2:
        a, b, c, d = matrix[0,0], matrix[0,1], matrix[1,0], matrix[1,1]
        A = float(a*d - b*c)
        return(A)
    else:
        print("Not a 2x2 matrix")

def det_3(matrix):
    # calculates determinant of a 3x3 matrix       
    if matrix.shape[1] == 3:
        a, b, c, d, e = matrix[0,0], matrix[0,1], matrix[0,2], matrix[1,0], matrix[1,1]
        f, g, h, i = matrix[1,2], matrix[2,0], matrix[2,1], matrix[2,2] 
        #d1 = float(e*i - f*h)
        #d2 = float(d*i - f*g)
        #d3 = float(d*h - e*g)
        #A = float(a*d1 - b*d2 + c*d3)
        A = float(a*e*i + b*f*g + c*d*h - c*e*g - b*d*i - a*f*h)
        return(A)
    else:
        print("not a 3x3 matrix")
        
def deter(matrix):
    # calculates determinant of any matrix
    total = 0
    if matrix.shape[1] == 2:
        det_2(matrix) # use 2x2 function
    elif matrix.shape[1] == 3:
        det_3(matrix) # use 3x3 function
    else:
        # store dimension of matrix: dim
        dim = matrix.shape[1]
        # initialize list of return values
        vals = []
        for i in range(0, dim):
            coeff = matrix[0,i] # pull coefficient from the root value
            new_matrix = np.delete(matrix, i, 0) # create new matrix without root row
            new_matrix = np.delete(new_matrix, i, 1) # remove root column from new matrix
            val = (det_3(new_matrix)) # perform 3d determinant calculation off the new matrix
            vals.append(val * coeff) # multiply by coefficient and append to value list
         
        # initialize total variable
        for i in range(len(vals)):
            if i % 2 == 0:
                total += vals[i]
            else:
                total -= vals[i]
                
        return total
            
    
        

In [92]:
#initialize 2x2, 3x3, and 4x4 matrices
from numpy import random

# 2x2
m2 = np.random.randint(1, 100, size=[2,2])

# 3x3
m3 = np.random.randint(1, 100, size=[3,3])

# 4x4
m4 = np.random.randint(1, 100, size=[4,4])

In [93]:
m2

array([[ 1, 89],
       [60, 77]])

In [94]:
m3

array([[49, 10, 83],
       [48, 18, 75],
       [69, 24, 78]])

In [95]:
m4

array([[70,  8, 31, 98],
       [77, 46, 69, 52],
       [34, 83, 27, 60],
       [46,  3, 21, 21]])

In [98]:
# 2x2 determinant calculation
print("manual:", det_2(m2))
print("built-in:", det(m2))

manual: -5263.0
built-in: -5262.9999999999945


In [99]:
# 3x3 determinant calculation
print("manual:", det_3(m3))
print("built-in:", det(m3))

manual: -12564.0
built-in: -12564.000000000007


In [141]:
# 4x4 determinant calculationdeter(m4)
print("manual:", deter(m4))
print("built-in:", det(m4))

manual: 8680170.0
built-in: 6650274.999999999


I thought if I built a function that would perform the 3x3 matrix determinant calculation on each column of the larger matrices and then perform the cumulative calculation on those values, I could find the determinant of larger matrices, but as you can see, that doesn't work. 

I also tried to check my 3x3 determinant against the product of the eigenvalues for the same 3x3 matrix, but got a different result:

In [143]:
det_three = np.prod(eigen_3(m3))
det_three

(145/3 + (-1/2 - sqrt(3)*I/2)*(8236217/54 + sqrt(104811600063)*I/6)**(1/3) + 26722/(9*(-1/2 - sqrt(3)*I/2)*(8236217/54 + sqrt(104811600063)*I/6)**(1/3)))*(145/3 + 26722/(9*(-1/2 + sqrt(3)*I/2)*(8236217/54 + sqrt(104811600063)*I/6)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(8236217/54 + sqrt(104811600063)*I/6)**(1/3))*(145/3 + 26722/(9*(8236217/54 + sqrt(104811600063)*I/6)**(1/3)) + (8236217/54 + sqrt(104811600063)*I/6)**(1/3))

In [92]:
# this is simply a scratchpad of a way I discarded to represent matrix positions, decided to leave it here to 
# show one of many different ways I tried to represent the determinant formula
a, b, c, d, e = matrix[0,0], matrix[0,1], matrix[0,2], matrix[1,0], matrix[1,1]
f, g, h, i = matrix[1,2], matrix[2,0], matrix[2,1], matrix[2,2] 
d1 = float((e * i) - (f * h))
d2 = float((d * i) - (g * h))
d3 = float((d * h) - (e * g))
A = float(abs((a * d1) - (b * d2) + (c * d3)))

I could not return the determinant for matrices 4x4 or larger